#!/usr/bin/python

bnchmrk="MIS"
benchmark="Maximal Independent Set"
checkProgram="../common/MISCheck"
dataDir = "../graphData/data"

tests = [
    [1, "randLocalGraph_J_5_100000000", "", ""],
    [1, "rMatGraph_J_5_100000000", "", ""],
    [1, "3Dgrid_J_100000000", "", ""]
    ]

import runTests
runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

