#!/usr/bin/python

bnchmrk="matching"
benchmark="Maximal Matching"
checkProgram="../common/matchingCheck"
dataDir = "../graphData/data"

tests = [
    [1, "randLocalGraph_E_5_100000000", "", ""],
    [1, "rMatGraph_E_5_100000000", "", ""],
    [1, "2Dgrid_E_100000000", "", ""],
    [1, "expGraph_E_50000000","",""],
    [1, "starGraph_E_500000000","",""],
    ]

import runTests
runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

